// components/ui/button.tsx
import * as React from "react"
import { Slot } from "@radix-ui/react-slot"
import { cva, type VariantProps } from "class-variance-authority"

import { cn } from "@/lib/utils"

const buttonVariants = cva(
  "inline-flex items-center justify-center whitespace-nowrap rounded-md text-sm font-medium ring-offset-white transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-gray-950 focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 dark:ring-offset-gray-950 dark:focus-visible:ring-gray-300",
  {
    variants: {
      variant: {
        default: "bg-gray-900 text-neutral-50 hover:bg-gray-900/90 dark:bg-gray-50 dark:text-neutral-900 dark:hover:bg-gray-50/90",
        destructive:
          "bg-red-500 text-neutral-50 hover:bg-red-500/90 dark:bg-red-900 dark:text-neutral-50 dark:hover:bg-red-900/90",
        outline:
          "border border-gray-200 bg-white hover:bg-gray-100 hover:text-neutral-900 dark:border-gray-800 dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-neutral-50",
        secondary:
          "bg-gray-100 text-neutral-900 hover:bg-gray-100/80 dark:bg-gray-800 dark:text-neutral-50 dark:hover:bg-gray-800/80",
        ghost: "hover:bg-gray-100 hover:text-neutral-900 dark:hover:bg-gray-800 dark:hover:text-neutral-50",
        link: "text-neutral-900 underline-offset-4 hover:underline dark:text-neutral-50",
      },
      size: {
        default: "h-10 px-4 py-2",
        sm: "h-9 rounded-md px-3",
        lg: "h-11 rounded-md px-8",
        icon: "h-10 w-10",
      },
    },
    defaultVariants: {
      variant: "default",
      size: "default",
    },
  }
)

export interface ButtonProps
  extends React.ButtonHTMLAttributes<HTMLButtonElement>,
    VariantProps<typeof buttonVariants> {
  asChild?: boolean
}

const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
  ({ className, variant, size, asChild = false, ...props }, ref) => {
    const Comp = asChild ? Slot : "button"
    return (
      <Comp
        className={cn(buttonVariants({ variant, size, className }))}
        ref={ref}
        {...props}
      />
    )
  }
)
Button.displayName = "Button"

export { Button, buttonVariants }

// src/lib/components/button.svelte
<script lang="ts">
  export let variant = 'primary';
  
  const styles = {
    primary: 'flex w-fit items-center justify-center gap-1 rounded-full border-2 tracking-wider transition-all h-12 px-6 text-sm text-primary-black border-primary-white bg-primary-white shadow-3xl   shadow-white/80 font-paragraph  font-medium drop-shadow-[3px_0_30px_rgba(254,254,254,0.472)] transition-all hover:drop-shadow-[10px_0_40px_rgba(254,254,254,0.472)] cursor-pointer',
    secondary: 'flex w-fit items-center justify-center gap-1 rounded-full border-2 tracking-wider transition-all h-12 px-6 text-sm text-neutral-500 hover:text-primary-white border-neutral-600 hover:border-primary-white bg-neutral-800 hover:bg-neutral-700 font-paragraph font-semibold tracking-wider cursor-pointer',
    danger: 'flex w-fit items-center justify-center gap-1 rounded-full border-2 tracking-wider transition-all h-12 px-6 text-sm text-white border-red-600 hover:border-red-500 bg-red-700 hover:bg-red-600 font-paragraph font-semibold tracking-wider cursor-pointer'
  };
</script>

<button
  class={styles[variant as keyof typeof styles]}
  {...$$restProps}
>
  <slot />
</button>
